source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'
gem 'rails-api'
gem 'pg', platform: :ruby

# Authentication and Registration mechanism.
gem 'devise'
gem 'foreman'

# Development and Test environment variables setup.
gem 'dotenv-rails'

# Allow for easy setup for Cross-Origin Response Sharing Policy.
gem 'rack-cors', :require => 'rack/cors'

# Provide a simple class-based authorization mechanism.
gem 'pundit'

group :production do
  gem 'therubyracer', platforms: :ruby
  gem 'rails_12factor'
  gem 'puma'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'factory_girl_rails'
  gem 'email_spec'
end
