source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'
gem 'rails-api'
gem 'pg', platform: :ruby

# Authentication and Registration mechanism.
gem 'devise'
gem 'foreman'

# Development and Test environment variables setup.
gem 'dotenv-rails'

# Allow for easy setup for Cross-Origin Response Sharing Policy.
gem 'rack-cors', :require => 'rack/cors'

# Provide a simple class-based authorization mechanism.
gem 'pundit'

# Provide an easy way to deal with image-uploads.
gem 'dragonfly'
gem 'dragonfly-s3_data_store'

# Templating API JSON responses.
gem 'rabl'

# JSON parser.
gem 'oj'

# This is used in web-client not backend.
# And it is to get around installing sass on Travis.
gem 'sass'


group :production do
  gem 'rails_12factor'
  gem 'puma'
	gem 'rack-cache', :require => 'rack/cache'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'factory_girl_rails'
  gem 'email_spec'
  gem 'rb-readline'
end
